name: CI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-push-container:
    name: Build Container and Publish
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      # - 
      #   name: Echo
      #   run: echo ${{ steps.get_version.outputs.VERSION }}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - 
        name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      -
        name: Build and Push Runtime
        uses: docker/build-push-action@v3
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: 
            ghcr.io/ejlevin1/flutter-web-builder:${{ steps.get_version.outputs.VERSION }}
          target: flutter-builder
          build-args: |
              FLUTTER_VERSION=${{ steps.get_version.outputs.VERSION }}